"""Assemble detection rules into a deployable pack: per-platform rule files, coverage, prerequisites."""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from . import __version__
from .choke import find_chokepoints
from .detections import AUDIT, Rule, build_rules, to_elastic, to_kql, to_sigma, to_spl
from .graph import AttackGraph
from .pathfinder import find_all_paths

FORMATS = ("sigma", "splunk", "sentinel", "elastic")
_EXT = {"sigma": ".yml", "splunk": ".spl", "sentinel": ".kql", "elastic": ".kql"}


@dataclass
class Pack:
    rules: list[Rule]
    meta: dict = field(default_factory=dict)
    points: list[dict] = field(default_factory=list)


def residual_points(graph: AttackGraph, assume_fixed: int = 0, top: int = 25,
                    max_depth: int = 20, max_paths: int = 10000) -> tuple[AttackGraph, list[dict], dict]:
    """Apply the top-N fixes virtually, then pick the monitor points that cover most of what remains."""
    paths = find_all_paths(graph, graph.tier0_nodes, max_depth, max_paths)
    work = graph.clone()
    fixed: list[dict] = []
    if assume_fixed > 0 and paths.paths:
        choke = find_chokepoints(graph, paths, max_fixes=assume_fixed)
        for fx in choke.fixes:
            work.remove_edge(fx.source_id, fx.target_id, fx.edge_type)
            fixed.append({"source": fx.source_name, "target": fx.target_name, "edge": fx.edge_type,
                          "paths": fx.paths_eliminated})
    work.retier()
    residual = find_all_paths(work, work.tier0_nodes, max_depth, max_paths)
    points: list[dict] = []
    if residual.paths:
        choke2 = find_chokepoints(work, residual, max_fixes=top)
        points = [{"source_id": f.source_id, "target_id": f.target_id, "edge_type": f.edge_type,
                   "paths": f.paths_eliminated, "cumulative_pct": f.cumulative_pct} for f in choke2.fixes]
    info = {"paths_total": paths.total_paths, "paths_residual": residual.total_paths, "assumed_fixed": fixed,
            "monitor_points": len(points),
            "coverage_pct": points[-1]["cumulative_pct"] if points else (100.0 if not residual.paths else 0.0),
            "truncated": paths.total_paths >= max_paths or residual.total_paths >= max_paths}
    return work, points, info


def build_pack(graph: AttackGraph, points: list[dict], info: dict | None = None, include_watches: bool = True) -> Pack:
    return Pack(build_rules(graph, points, include_watches), dict(info or {}), points)


def prerequisites(rules: list[Rule]) -> list[dict]:
    needed: dict[str, list[str]] = {}
    for r in rules:
        for key in r.audit:
            needed.setdefault(key, []).append(r.slug)
    out = []
    for key, used_by in needed.items():
        sub, extra = AUDIT[key]
        out.append({"subcategory": sub, "command": f'auditpol /set /subcategory:"{sub}" /success:enable /failure:enable',
                    "note": extra, "needed_by": used_by})
    return out


def _coverage_md(pack: Pack) -> str:
    m = pack.meta
    out = ["# PathCutter detection pack", "",
           f"Generated by PathCutter {__version__}. {len(pack.rules)} rules.", ""]
    if m:
        fixed = m.get("assumed_fixed") or []
        out += [f"- Attack paths today: {m.get('paths_total', '?')}; assumed fixed: {len(fixed)} edge(s); residual paths: {m.get('paths_residual', '?')}",
                f"- Monitor points chosen: {m.get('monitor_points', '?')}, covering {m.get('coverage_pct', '?')}% of the residual paths"]
        if m.get("truncated"):
            out.append("- Path counts are capped and therefore lower bounds.")
        out.append("")
    out += ["## Rules", "", "| Rule | Level | Events | Monitors | Covers |", "|---|---|---|---|---|"]
    for r in pack.rules:
        out.append(f"| `{r.slug}` | {r.level} | {', '.join(map(str, r.event_ids))} | {len(r.objects)} object(s) | {len(r.covers)} edge(s) |")
    for r in pack.rules:
        out += ["", f"### {r.title}" + (f" (part {r.part})" if r.part > 1 else ""), "", f"`{r.slug}` - id `{r.id}` - {r.level}", "", r.description, ""]
        if r.objects:
            out.append("Monitors: " + ", ".join(f"`{o}`" for o in r.objects[:15]) + (" ..." if len(r.objects) > 15 else ""))
        if r.actors:
            out.append("")
            out.append("Principals who can abuse the covered edges (watchlist): " + ", ".join(f"`{a}`" for a in r.actors))
        if r.covers:
            out += ["", "Covered edges:"] + [f"- `{c['source']}` -[{c['edge']}]-> `{c['target']}` ({c['paths']} path(s))" for c in r.covers[:15]]
        out += ["", "Validate in a lab:", "", f"    {r.test_command}", "", f"Expect: {r.expected}", "", "If it fires:"] + [f"1. {s}" for s in r.response]
    return "\n".join(out) + "\n"


def _prereq_md(pack: Pack) -> str:
    out = ["# Audit prerequisites", "",
           "A detection is only as good as the log. These Advanced Audit Policy subcategories must be enabled",
           "on the domain controllers (or the hosts named in the rules) for the rules in this pack to see events.", ""]
    for p in prerequisites(pack.rules):
        out += [f"## {p['subcategory']}", "", f"    {p['command']}", ""]
        if p["note"]:
            out += [p["note"], ""]
        out += ["Needed by: " + ", ".join(f"`{s}`" for s in p["needed_by"]), ""]
    return "\n".join(out)


def write_pack(pack: Pack, out_dir: str | Path, formats: tuple[str, ...] = FORMATS, index: str = "wineventlog") -> list[Path]:
    out = Path(out_dir)
    written: list[Path] = []

    def put(path: Path, text: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        written.append(path)

    for fmt in formats:
        for r in pack.rules:
            if fmt == "sigma":
                text = to_sigma(r)
            elif fmt == "splunk":
                text = f"-- {r.title} [{r.id}]\n-- Windows TA (XmlWinEventLog). Adjust index/sourcetype to your environment.\n" + to_spl(r, index) + "\n"
            elif fmt == "sentinel":
                text = f"// {r.title} [{r.id}]\n" + to_kql(r) + "\n"
            else:
                text = f"// {r.title} [{r.id}]\n" + to_elastic(r) + "\n"
            put(out / fmt / (r.slug + _EXT[fmt]), text)
    put(out / "coverage.md", _coverage_md(pack))
    put(out / "prerequisites.md", _prereq_md(pack))
    put(out / "coverage.json", json.dumps({
        "generator": f"pathcutter {__version__}", "meta": pack.meta,
        "rules": [{"id": r.id, "slug": r.slug, "title": r.title, "level": r.level, "event_ids": r.event_ids,
                   "objects": r.objects, "covers": r.covers, "actors": r.actors, "tags": r.tags,
                   "audit": [AUDIT[a][0] for a in r.audit], "test_command": r.test_command, "expected": r.expected,
                   "response": r.response} for r in pack.rules],
        "prerequisites": prerequisites(pack.rules)}, indent=2) + "\n")
    return written
