"""AD rights knowledge, loaded from data/rights.json (the single source of truth).

ingest.py (collector right names -> edge types), ps_rules.py (PowerShell property GUIDs, dsacls letters) and
tools/Export-AdDenyAces.ps1 (generated by tools/gen_collector_table.py) all read from here. To teach PathCutter a new
right, add ONE entry to data/rights.json, run tools/gen_collector_table.py, and the registry tests tell you if
anything else (an EdgeType, help text, a detection) is still missing.
"""
from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

DATA = Path(__file__).parent / "data" / "rights.json"


@lru_cache(maxsize=1)
def load() -> dict:
    return json.loads(DATA.read_text(encoding="utf-8"))


def collector_ace() -> dict[str, str]:
    return dict(load()["collector_ace"])


def collector_edge() -> dict[str, str]:
    return dict(load()["collector_edge"])


def local_group_rid() -> dict[str, str]:
    return dict(load()["local_group_rid"])


def gpo_changes() -> dict[str, str]:
    return dict(load()["gpo_changes"])


def dsacls_letters() -> dict[str, str]:
    return dict(load()["dsacls_letters"])


def property_guids() -> dict[str, str]:
    """schema / extended-right GUID -> lower-case name."""
    return {p["guid"]: p["name"] for p in load()["properties"] if p.get("guid")}


def _by_kind(kind: str) -> dict[str, str]:
    return {p["name"]: p["edge"] for p in load()["properties"] if p["kind"] == kind and p.get("edge")}


def write_property_edges() -> dict[str, str]:
    return _by_kind("write_property")


def extended_right_edges() -> dict[str, str]:
    return _by_kind("extended_right")


def read_property_edges() -> dict[str, str]:
    return _by_kind("read_property")


def deny_collector_ids() -> dict[str, str]:
    """name -> identifier used in the PowerShell collector's GUID table, for rights the collector can see denies on."""
    return {p["guid"]: p["deny_collector"] for p in load()["properties"] if p.get("deny_collector") and p.get("guid")}
